### ISSUE TITLE
Add color to operation symbols and the “equals” symbol

### ISSUE THREAD

**Issue by niczapata** [NvChad/base46#160]
Comparison between morhetz grubvox and Base46 gruvbox

morhetz grubvox
![image](https://user-images.githubusercontent.com/35777697/219541613-bff26908-3838-4ff2-8eea-2ad49219cb5f.png)

Base46 gruvbox
![image](https://user-images.githubusercontent.com/35777697/219541815-9626216d-21aa-44d7-a1d1-fe5d19b5bc38.png)

Only “chocolate” and “falcon” themes have coloured operators, the rest of the themes are white or black.

**Comment by siduck** [comment]
@NicolasZapata will do it today so wait up!

**Comment by niczapata** [comment]
@siduck Ok, thank you :) 👍

**Comment by siduck** [comment]
yo @NicolasZapata  sorry I'll include it in v2.0 of nvchad so within this month! For now just override the hl group 

```lua

M.ui = {

  hl_override = {
     Operator = {
        fg = "green"
     }
  }
  
}
```

https://nvchad.com/config/theming

**Comment by niczapata** [comment]
Don't worry, thanks for the info anyway 🙂. 

Best regards.

**Comment by siduck** [comment]
@NicolasZapata should be fixed by now

**Comment by niczapata** [comment]
I already updated NvChad, but the problem was not fixed :(

best regards

**Comment by siduck** [comment]
> I already updated NvChad, but the problem was not fixed :(
> 
> best regards

update the plugin i.e do Lazy sync

**Comment by siduck** [comment]
i hope you're using nvchad v2.0

**Comment by niczapata** [comment]
Hi @siduck, yes, I'm using nvchad v2.0, GitHub's theme is really cool.

I've sent you a pull request, if you want to check it.

Best regards.
